application: epigene-db
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /images
  static_dir: images
  http_headers:
    Access-Control-Allow-Origin: '*' #http://epigenes.autosome.org
