json.hgnc_symbol  @histone.hgnc_symbol
json.hgnc_id  @histone.hgnc_id
json.hgnc_name  @histone.hgnc_name
json.gene_id  @histone.gene_id
json.uniprot_ac  @histone.uniprot_ac
json.uniprot_id  @histone.uniprot_id
json.domain  @histone.domain
json.mgi_symbol  @histone.mgi_symbol
json.mgi_id  @histone.mgi_id
json.uniprot_ac_mm  @histone.uniprot_ac_mm
json.uniprot_id_mm  @histone.uniprot_id_mm
json.gene_tag  @histone.gene_tag
json.gene_desc  @histone.gene_desc
json.complex_name  @histone.complex_name
json.targeted_by_protein  @histone.targeted_by_protein
json.targeted_by_complex  @histone.targeted_by_complex
json.pmid  @histone.pmid
json.comment  @histone.comment
json.status  @histone.status
