json.group_name  @protein_complex.group_name
json.complex_name  @protein_complex.complex_name
json.genes_in_complex  @protein_complex.genes_in_complex
json.alternative_name  @protein_complex.alternative_name
json.protein  @protein_complex.protein
json.uniprot_id  @protein_complex.uniprot_id
json.pmid_complex  @protein_complex.pmid_complex
json.function  @protein_complex.function
json.pmid_function  @protein_complex.pmid_function
json.target  @protein_complex.target
json.specific_target  @protein_complex.specific_target
json.product  @protein_complex.product
json.uniprot_id_target  @protein_complex.uniprot_id_target
json.pmid_target  @protein_complex.pmid_target
json.comment  @protein_complex.comment
json.status  @protein_complex.status
